import { parseEventInput } from "../../../../app/data/event-validation";
import { getAllEvents, getEventById, saveEvent } from "../../../../app/data/events-store";
import type { Event } from "../../../../app/data/types";
import type { AdminAuthData } from "../auth";
import { logSafe, writeAuditRecord } from "../../observability";

interface Env {
  VFC_SUBMISSIONS: KVNamespace;
}

export const onRequestGet: PagesFunction<Env> = async ({ env }) => {
  const events = await getAllEvents(env);
  return Response.json({ events });
};

export const onRequestPost: PagesFunction<Env, string, AdminAuthData> = async ({ request, env, data }) => {
  const actor = data.adminActor;
  const requestId = data.requestId;
  if (!actor || !requestId) {
    return Response.json({ error: "Authenticated admin identity missing" }, { status: 500 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = parseEventInput(body, true);
  if ("error" in parsed) {
    return Response.json({ error: parsed.error ?? "Invalid event payload" }, { status: 400 });
  }

  if (parsed.input.id) {
    return Response.json({ error: "Event id is generated by the server" }, { status: 400 });
  }
  const eventId = crypto.randomUUID();

  const existing = await getEventById(env, eventId);
  if (existing) {
    return Response.json({ error: "An event with this id already exists" }, { status: 409 });
  }

  const event: Event = {
    id: eventId,
    title: parsed.input.title ?? "",
    description: parsed.input.description ?? "",
    date: parsed.input.date ?? "",
    time: parsed.input.time ?? "",
    location: parsed.input.location ?? "",
    cafeId: parsed.input.cafeId,
    imageUrl: parsed.input.imageUrl,
    mapUrl: parsed.input.mapUrl,
    status: parsed.input.status ?? "published",
    tags: parsed.input.tags ?? [],
    createdAt: new Date().toISOString(),
  };

  await saveEvent(env, event, actor);

  const timestamp = new Date().toISOString();
  await writeAuditRecord(env.VFC_SUBMISSIONS, {
    timestamp,
    actor,
    action: "event.create",
    recordType: "event",
    recordId: event.id,
    requestId,
    changes: { newStatus: event.status },
  });
  logSafe({
    event: "admin_mutation_succeeded",
    level: "info",
    requestId,
    actor,
    action: "event.create",
    recordType: "event",
    recordId: event.id,
    status: 201,
  });

  return Response.json({ event }, { status: 201 });
};
